version: '3'

services:
  mysql:
    image: mysql:5
    container_name: blc23d01_usersCrud
    ports: [ "3306:3306" ]
    volumes: [ "./db:/docker-entrypoint-initdb.d" ]
    environment: [ "MYSQL_ROOT_PASSWORD=root" ]
